// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Connection struct {
	ID           string         `json:"id"`
	UserID       string         `json:"userId"`
	Provider     string         `json:"provider"`
	Email        string         `json:"email"`
	Token        string         `json:"token"`
	RefreshToken sql.NullString `json:"refreshToken"`
}

type Session struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Expiry int64  `json:"expiry"`
}

type User struct {
	ID     string `json:"id"`
	Active bool   `json:"active"`
}
